<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Lecture29Pipelining(b).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive # now this can behave as a webpage jaha user apna data deta hai
drive.mount('/content/drive')

# THESE STEPS ARE A CUMMULATION OF ALL THE TOPICS TAUGHT PREVIOUSLY

Mounted at /content/drive


In [3]:
import pickle
# decoding the ml mdoel
ohe_sex = pickle.load(open('/content/drive/MyDrive/models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('/content/drive/MyDrive/models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('/content/drive/MyDrive/models/clf.pkl', 'rb'))

In [6]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
import numpy as np
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [7]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [8]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [9]:
test_input_sex

array([[0., 1.]])

In [10]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [11]:
test_input_embarked

array([[0., 0., 1.]])

In [12]:
test_input_age = test_input[:,2].reshape(1,1)

In [13]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)
test_input_transformed.shape

(1, 10)

In [14]:
clf.predict(test_input_transformed)

array([0])