<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Changing Datatypes & Array Operations & Array Functions

In [5]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12 , dtype = float).reshape(3,4)
a3 = np.arange(40).reshape(2,4,5)
a4 = np.arange(10 , dtype = np.int32)

In [6]:
# Change datatype to any other
a1.astype(np.int32) # extra memory usage prevent karne ke liye
a1.astype(bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
# Array Operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12 , 24).reshape(3,4)

In [19]:
# Scalar Operations (1 scalar with 1 tensor)
print(a1 * 2) #Arithmetic
print(a2 > 15) #Relational

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [18]:
# Vector Operations (Dono same shape ki tensors hain)
print(a1 + a2) #Arithmetic
print(a2 > a1) #Relational

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [21]:
# Array Functions
a1 = np.random.random((3 , 3))
a1 = np.round(a1 * 100)
print(a1)

[[14.  4.  7.]
 [41. 19. 62.]
 [68. 82. 55.]]


In [24]:
# Basic Operns
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

# Har row mei min item -> (axis = 1 => row & 0 => col)#IMP
print(np.min(a1 , axis = 1))

82.0
4.0
352.0
5806316010880.0
[ 4. 19. 55.]


In [29]:
# Statstical Oprns
print(np.mean(a1))
print(np.median(a1 , axis = 0))
print(np.std(a1))
print(np.var(a1 , axis = 1))

39.111111111111114
[41. 19. 55.]
27.391987654318207
[ 17.55555556 308.22222222 121.55555556]


In [30]:
# Trignometric functions
np.sin(a1)

array([[ 0.99060736, -0.7568025 ,  0.6569866 ],
       [-0.15862267,  0.14987721, -0.7391807 ],
       [-0.89792768,  0.31322878, -0.99975517]])

In [31]:
# Dot Product (matrix multiplcn)
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12 , 24).reshape(4 , 3)
np.dot(a1 , a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [41]:
# Some more functions
a1 = np.arange(1 , 11)
np.log(a1)
np.exp(a1)
a1 = np.random.random((2 , 3))*100
print("normal => \n" , a1)
print("rounded => \n" , np.round(a1))
np.floor(a1)
np.ceil(a1)

normal => 
 [[94.80245212 44.53539565 26.72294238]
 [49.38256501 59.32406309 24.13352418]]
rounded => 
 [[95. 45. 27.]
 [49. 59. 24.]]


array([[95., 45., 27.],
       [50., 60., 25.]])