<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
# Statistical + Utility + Set Functions
import numpy as np

In [55]:
# np.sort -> return a sorted copy of an array
a = np.random.randint(1 , 100 , 15)
a = np.sort(a)
print(a)

[ 7 11 11 26 37 45 47 52 72 77 78 92 93 95 98]


In [4]:
np.sort(a)[::-1] # for descending order

array([94, 93, 85, 75, 74, 73, 72, 72, 66, 65, 64, 41, 33, 23,  6])

In [6]:
# for 2D array -> axis = 1 or 0
b = np.random.randint(1 , 100 , 15).reshape(5 , 3)
print(np.sort(b) , "\n")
print(np.sort(b , axis = 0))

[[33 41 96]
 [ 4 60 81]
 [21 65 91]
 [18 31 71]
 [32 47 69]] 

[[18 21  4]
 [33 31 32]
 [69 47 41]
 [81 60 65]
 [91 96 71]]


In [9]:
# np.append -> appends values along the mentioned axis
np.append(a , 200)
np.append(b , np.ones((b.shape[0] , 1)) , axis = 1)

array([[33., 96., 41.,  1.],
       [81., 60.,  4.,  1.],
       [91., 21., 65.,  1.],
       [18., 31., 71.,  1.],
       [69., 47., 32.,  1.]])

In [11]:
# np.concatenate -> concates a seq of arrays along an existing axis (similar to stacking)
c = np.arange(6).reshape(2 , 3)
d = np.arange(6 , 12).reshape(2 , 3)

print(c)
print(d)
print(np.concatenate((c , d) , axis = 1)) #hstack
print(np.concatenate((c , d) , axis = 0)) #vstack

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
# np.unique -> to get the unique values from an array given as parameter in np.unqiue
a = np.array([1 , 1 , 2 , 2 , 3 , 4 , 5 , 5 , 5 , 5])
print(np.unique(a)) ;

[1 2 3 4 5]


In [26]:
# np.expand_dims -> to convert 1D to 2D to 3D so on etc
a = np.array([1,2,3])
print(a.shape)
a = np.expand_dims(a , axis = 0)
print(a.shape)
print(a)
a = np.expand_dims(a , axis = 1)
print(a.shape)
print(a)

(3,)
(1, 3)
[[1 2 3]]
(1, 1, 3)
[[[1 2 3]]]


In [31]:
# np.where -> returns the indices of elements in an i/p array where given condn is satisfied
a = np.random.randint(1 , 100 , 10)
print(a)

[32 85 93 18 89 10 38 49 40 35]


In [32]:
np.where(a > 50)

(array([1, 2, 4]),)

In [33]:
# replace all values > 50 with 0
#np.where(condition , true , false)
np.where(a > 50 , 0 , a)

array([32,  0,  0, 18,  0, 10, 38, 49, 40, 35])

In [34]:
# np.argmax -> returns indices of max element of array in a part. axis (||ly np.argmin(a))
np.argmax(a)

np.int64(2)

In [35]:
# np.cumsum -> cummulative sum of an array along a part axis
np.cumsum(a)

array([ 32, 117, 210, 228, 317, 327, 365, 414, 454, 489])

In [36]:
np.cumsum(b) # 2D mei agar axis specify nahi kiya toh 1D mei convert karega then cumsum

array([ 33, 129, 170, 251, 311, 315, 406, 427, 492, 510, 541, 612, 681,
       728, 760])

In [37]:
np.cumsum(b , axis = 0)

array([[ 33,  96,  41],
       [114, 156,  45],
       [205, 177, 110],
       [223, 208, 181],
       [292, 255, 213]])

In [38]:
# np.percentile -> nth percentile of given data along specific axis
np.percentile(a , 100) #100th percentile -> max

np.float64(93.0)

In [39]:
# np.histogram -> freq count in a given range (binSize decide karo and utni space mei kitne no.s => 0 to 10 then 11 to 20 then 21 to 30)
np.histogram(a , bins = [0 , 10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 , 90 , 100])

(array([0, 2, 0, 3, 2, 0, 0, 0, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [40]:
# np.corrcoed -> correlation coefficient ?
salary = np.array([20000 , 40000, 25000, 35000, 60000])
experience = np.array([1 , 3 , 2 , 4 , 2])

np.corrcoef(salary,experience) # salary ka salary ke saath then salary ka exp ke saath then exp ka sal ke saath then exp ka exp ke saath -> corr matrix aa gayi

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [42]:
# np.isin -> given array mei mult. items ko search karke batayega if they are in the array or not
items = [6 , 23 , 33 , 41 , 64 , 65 , 66 , 72 , 72 , 73 , 74 , 75 , 85 , 93 , 94]
a[np.isin(a , items)]

array([85, 93])

In [46]:
# np.flip -> reverses the order of array elements along the specified axis , preserving the shape of the array
print(a)
np.flip(a)

[32 85 93 18 89 10 38 49 40 35]


array([35, 40, 49, 38, 10, 89, 18, 93, 85, 32])

In [47]:
print(b)
np.flip(b) #row-wise & colwise both flip but if axis mentioned then NOT

[[33 96 41]
 [81 60  4]
 [91 21 65]
 [18 31 71]
 [69 47 32]]


array([[32, 47, 69],
       [71, 31, 18],
       [65, 21, 91],
       [ 4, 60, 81],
       [41, 96, 33]])

In [49]:
# np.put -> replaces specfic elements of array with indices and unki nayi value
np.put(a , [0 , 1] , [110 , 530])
a

array([110, 530,  93,  18,  89,  10,  38,  49,  40,  35])

In [50]:
# np.delete -> returns a new array with the deletion of sub-arrays
np.delete(a , [0,1])

array([93, 18, 89, 10, 38, 49, 40, 35])

In [56]:
# Set Functions

In [58]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)
#||ly isme np.intersect1d , setdiff1d , setxor1d , in1d etc.

array([1, 2, 3, 4, 5, 6, 7])

In [60]:
# np.clip -> Clip(limit) the values in an array
np.clip(a , a_min = 25 , a_max = 75)

array([25, 25, 25, 26, 37, 45, 47, 52, 72, 75, 75, 75, 75, 75, 75])