<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy Array Generation

In [2]:
import numpy as np
a = np.array([1,2,3])
print(type(a)) #vector

<class 'numpy.ndarray'>


In [3]:
b = np.array([[1,2,3] , [4,5,6]]) #2D matrix , ||ly tensor and so on
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# dtype
c = np.array([1,2,3] , dtype = float)
d = np.array([1,2,3] , dtype = bool)
e = np.array([1,2,3] , dtype = complex)
print(c)
print(d)
print(e)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [5]:
# np.arange
np.arange(1 , 11 , 2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
# For initializing arrays

np.ones((3,4))
np.zeros((3,4))
np.random.random((3,4)) # by default dtype = float

array([[0.7152985 , 0.42956155, 0.12895885, 0.54555272],
       [0.10910066, 0.04218003, 0.7568227 , 0.07568198],
       [0.18369202, 0.78549633, 0.45962839, 0.35351612]])

In [8]:
# Linearly Spaced Array Generation -> sp ep and no. of items u want to generate
np.linspace(-10,10,10) # (equal dist se seperated points)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [9]:
# Identity Matrix Creation
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Shape of a 1D Tensor
a = np.array([1,2,3])
print(a.shape)
b = np.array([[1,2,3]])
print(b.shape)

(3,)
(1, 3)
