<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# TOPIC 1 =>
  #  Numpy Array vs Python Lists
import numpy as np
import time as t

In [3]:
# Speed ->

# List
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
start = t.time()
for i in range(len(a)) :
  c.append(a[i] + b[i])

print(t.time() - start)

# Numpy Array
a = np.arange(10000000)
b = np.arange(10000000 , 20000000)

start = t.time()
c = a + b
print(t.time() - start)

5.086996078491211
0.31195664405822754


In [4]:
# Memory ->

# List
a = [i for i in range(10000000)]
import sys

print(sys.getsizeof(a))
# Numpy Array
a = np.arange(10000000 ,dtype=np.int32) #normal int64 same size occupy karega
print(sys.getsizeof(a))

89095160
40000112


In [5]:
# Convinience ->

# For loop nahi likhna padhega fir baaki kayi cheezo ke direct functions fir math oprns etc

In [14]:
#TOPIC 2 -> Advanced Indexing
a = np.arange(24).reshape(6,4)
# 1)Fancy Indexing -> Jab NO pattern for fetching then give a list and usme joh chahiye voh provide kardo
print(a[[0,2,3,5]])
print(a[:,[0,2,3]]) # All rows but only 0th 2nd and 3rd column

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]
[[88 98 65  5]
 [75 62 73 10]
 [13 41 26 93]
 [63 57 16 68]
 [72 85 68 29]
 [69 21 33 95]]


In [21]:
a = np.random.randint(1 , 100 , 24).reshape(6 , 4) # 24 items randomly from 1 to 100
print(a)
# 2)Boolean Indexing -> Fetching on the basis of a condn
b = a > 50 # Now this is a boolean Array and can be used as a BOOLEAN MASK #IMP
print(b)
print(a[b]) # Jaha jaha True hogi value only those
print(a[~(a % 2 == 0) & (a > 50)]) # Yaha bitwise AND aayega kyuki boolean values ke saath deal kar rahe

[[89 11  1 35]
 [34 54 53 27]
 [44 43 66 86]
 [59 47 25 37]
 [58 80  4 26]
 [97 30 68 99]]
[[ True False False False]
 [False  True  True False]
 [False False  True  True]
 [ True False False False]
 [ True  True False False]
 [ True False  True  True]]
[89 54 53 66 86 59 58 80 97 68 99]
[89 53 59 97 99]
