<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Numpy Array Generation

<class 'numpy.ndarray'>


In [21]:
import numpy as np
a = np.array([1,2,3])
print(type(a)) #vector

<class 'numpy.ndarray'>


In [6]:
b = np.array([[1,2,3] , [4,5,6]]) #2D matrix , ||ly tensor and so on
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
# dtype
c = np.array([1,2,3] , dtype = float)
d = np.array([1,2,3] , dtype = bool)
e = np.array([1,2,3] , dtype = complex)
print(c)
print(d)
print(e)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [10]:
# np.arange
np.arange(1 , 11 , 2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
# For initializing arrays

np.ones((3,4))
np.zeros((3,4))
np.random.random((3,4)) # by default dtype = float

array([[0.6956597 , 0.24342841, 0.63659824, 0.79982014],
       [0.0929122 , 0.84515827, 0.57319577, 0.57842006],
       [0.87101455, 0.14874022, 0.23956946, 0.62015647]])

In [18]:
# Linearly Spaced Array Generation -> sp ep and no. of items u want to generate
np.linspace(-10,10,10) # (equal dist se seperated points)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [20]:
# Identity Matrix Creation
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])