<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Iterating & Reshaping + Stacking & Spliting
import numpy as np

In [3]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3 , 4)
a3 = np.arange(27).reshape(3 , 3 , 3)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
for i in a1 :
  print(i)

0
1
2
3
4
5
6
7
8
9


In [6]:
for i in a3 :
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [7]:
for i in np.nditer(a3) :  # nd iter will iterate over all items by 1) Converting 3D to 1D then iterating over that 1D array
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [9]:
# Reshaping ->

#Transpose
np.transpose(a2)
a2.T #Same as up

#Ravel -> Kitne bhi dim ki array ko 1D mei convert kardega
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [13]:
# Stacking -> (Shape same hona chahiye isme)
a4 = np.arange(12).reshape(3 , 4)
a5 = np.arange(12 , 24).reshape(3 , 4)

# Vertical Stacking => Ek ke upar ek => 2*2 ke 2 Array then 4*2 ban jayega
print(np.vstack((a4 , a5 , a4 , a5)))

#Horizontal Stacking
print(np.hstack((a4 , a5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [17]:
# Spliting -> Opposite of Stacking

# Horizontal Split mei | = line of split #IMP
print(np.hsplit(a4 , 4)) # ENSURE -> Equal size ke rahenge saare
# Vertical Split mei - = line of split #IMP
print(np.vsplit(a5 , 3))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]
