<a href="https://colab.research.google.com/github/number1coder01/Machine-Learning/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Indexing & Slicing
import numpy as np

In [14]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3 , 4)
a3 = np.arange(27).reshape(3 , 3 , 3)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
# Indexing
print(a1[-1])
print(a1[2])
print(a2[0 , 2])
print(a3[0 , 1 , 1]) # same as [0][1][1]

9
2
2
4


In [12]:
# Slicing -> Ek saath multiple items fetch
# Trick -> Ask urself Konsi rows chahiye and konse cols then write them
print(a1[2 : 5]) # sp to ep - 1 , agar ep last idx tak chahiye toh write nothing i.e.(1:)
print(a1[2 : 5 : 2])

[2 3 4]
[2 4]


In [16]:
# 2D Slicing
print(a2[0 , :]) # Pehla row with all columns
print(a2[ : , 2]) # 3rd col with all rows
print(a2[1: , 1 : 3]) # 1st row onwards and col 1 to 2
print(a2[::2 , ::3])
print(a2[0::2 , 1::2])
print(a2[1 , 0 :: 3])

[0 1 2 3]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]


In [20]:
# 3D Slicing
print(a3[0 , 1])
print(a3[1 , : , 1]) # 2nd wali 2D array ka 1st col and all rows
print(a3[::2 , 0 , :: 2])

[3 4 5]
[10 13 16]
[[ 0  2]
 [18 20]]
